-- PRODUCTS (20 entries)
INSERT INTO products (ProductId, name, price, type, description) VALUES
-- Football (20 products)
(1, 'Pro Football Helmet', 149.99, 'football', 'Full-size adult helmet with impact-resistant shell and foam padding'),
(2, 'Official NFL Game Ball', 89.99, 'football', 'Regulation size composite leather football for game play'),
(3, 'Football Shoulder Pads', 79.99, 'football', 'Lightweight shoulder pads with adjustable straps for youth players'),
(4, 'Football Cleats', 64.99, 'football', 'Molded rubber cleats with ankle support and cushioned insole'),
(5, 'Football Gloves', 34.99, 'football', 'Receiver gloves with sticky grip and breathable mesh back'),
(6, 'Practice Football', 24.99, 'football', 'Durable rubber practice ball suitable for all weather conditions'),
(7, 'Football Girdle with Pads', 44.99, 'football', 'Integrated hip and thigh padding in a compression girdle'),
(8, 'Football Kicking Tee', 9.99, 'football', 'Adjustable kicking tee compatible with kickoffs and field goals'),
(9, 'Football Training Cone Set', 19.99, 'football', 'Set of 20 bright orange cones for agility and route drills'),
(10, 'Football Rib Protector', 39.99, 'football', 'Padded rib guard that fits under the shoulder pads'),
(11, 'QB Wristband Playbook', 14.99, 'football', 'Wristband with clear window for holding play call sheets'),
(12, 'Football Agility Ladder', 29.99, 'football', '12-rung flat agility ladder with carry bag for footwork drills'),
(13, 'Football Mouthguard', 7.99, 'football', 'Boil-and-bite mouthguard with tether strap for helmet attachment'),
(14, 'Football Down Marker Set', 59.99, 'football', 'Sideline down marker and yardage chain set for official games'),
(15, 'Football Catching Trainer', 49.99, 'football', 'Rebounding net for solo catching and route-running practice'),
(16, 'Football Compression Shirt', 27.99, 'football', 'Moisture-wicking under-armour shirt with flat-seam construction'),
(17, 'Passing Quarterback Net', 89.99, 'football', 'Portable standalone target net for throwing accuracy training'),
(18, 'Football Dummy Tackle Bag', 74.99, 'football', 'Free-standing foam tackle bag weighted at the base'),
(19, 'Football Scoreboard', 199.99, 'football', 'Battery-powered portable scoreboard with two-digit display'),
(20, 'Football Pump and Needle Kit', 12.99, 'football', 'Dual-action air pump with three inflation needles for balls'),

-- Baseball (20 products)
(21, 'Maple Wood Baseball Bat', 99.99, 'baseball', 'Pro-grade maple wood bat with cupped end and lacquered finish'),
(22, 'Baseball Batting Helmet', 49.99, 'baseball', 'Single-flap ABS batting helmet with foam inner liner'),
(23, 'Baseball Catcher Gear Set', 179.99, 'baseball', 'Full catchers set including mask, chest guard, and shin guards'),
(24, 'Rawlings Baseball Glove', 119.99, 'baseball', '12-inch leather infield glove with open back wrist adjustment'),
(25, 'Official League Baseball', 14.99, 'baseball', 'Cowhide leather baseball with raised red cotton stitching'),
(26, 'Baseball Batting Tee', 39.99, 'baseball', 'Rubber tee with telescoping post adjustable from 22 to 34 inches'),
(27, 'Baseball Pitching Machine', 349.99, 'baseball', 'Entry-level pitching machine with speed range of 15 to 45 mph'),
(28, 'Baseball Cleats', 59.99, 'baseball', 'Molded plastic cleat baseball shoe with TPU outsole'),
(29, 'Baseball Batting Gloves', 29.99, 'baseball', 'Sheepskin leather palm gloves with hook-and-loop wrist closure'),
(30, 'Baseball Chest Protector', 54.99, 'baseball', 'Lightweight foam chest guard for youth catchers'),
(31, 'Baseball Pitching Rubber', 24.99, 'baseball', 'Regulation white pitcher rubber with anchor spikes'),
(32, 'Baseball Batting Cage Net', 159.99, 'baseball', '10x10x20 foot batting cage netting with tie-down cords'),
(33, 'Baseball Fielding Trainer', 34.99, 'baseball', 'Soft foam practice ball for indoor fielding reps'),
(34, 'Baseball Helmet Bag', 19.99, 'baseball', 'Mesh ventilated bag holds up to four batting helmets'),
(35, 'Pitching Mound Portable', 249.99, 'baseball', 'Fiberglass portable mound with regulation 10-inch height'),
(36, 'Baseball Scorebook', 12.99, 'baseball', '24-game official scoring book with pitch count columns'),
(37, 'Baseball First Base Mitt', 109.99, 'baseball', '13-inch first baseman glove with scoop and palm pad'),
(38, 'Baseball Training Balls Bucket', 44.99, 'baseball', 'Bucket of 24 reduced-impact training baseballs'),
(39, 'Baseball Bases Set', 69.99, 'baseball', 'Set of three anchor-able bases plus home plate in white rubber'),
(40, 'Baseball Pine Tar Stick', 8.99, 'baseball', 'Legal pine tar applicator for improved grip on bat handle'),

-- Basketball (20 products)
(41, 'NBA Official Game Basketball', 159.99, 'basketball', 'Full-grain leather indoor basketball size 7 official weight'),
(42, 'Adjustable Basketball Hoop', 299.99, 'basketball', 'Portable hoop adjustable from 7.5 to 10 feet with fillable base'),
(43, 'Basketball Backboard Pad', 39.99, 'basketball', 'Foam backboard padding with velcro straps for player safety'),
(44, 'Basketball Shoes High-Top', 109.99, 'basketball', 'High-ankle cushioning shoe with herringbone rubber outsole'),
(45, 'Basketball Knee Pads', 24.99, 'basketball', 'Compression sleeve knee pads with gel insert for floor play'),
(46, 'Basketball Training Aid', 19.99, 'basketball', 'Dribble goggles restricting downward vision to improve ballhandling'),
(47, 'Basketball Shooting Sleeve', 14.99, 'basketball', 'Compression arm sleeve with elbow pad for shooting consistency'),
(48, 'Mini Basketball Hoop Set', 49.99, 'basketball', 'Over-the-door mini hoop with foam ball for indoor use'),
(49, 'Basketball Ball Pump', 12.99, 'basketball', 'Dual-action floor pump with pressure gauge and needle'),
(50, 'Basketball Rebounder Net', 129.99, 'basketball', 'Solo shooting rebounder that returns made shots to the shooter'),
(51, 'Basketball Training Cones', 17.99, 'basketball', 'Set of 12 low-profile dribble cones for ball-handling circuits'),
(52, 'Basketball Jersey Set', 89.99, 'basketball', 'Set of 12 reversible jerseys in two colors with numbering'),
(53, 'Basketball Scoreboard', 229.99, 'basketball', 'Wall-mount scoreboard with clock timer and buzzer'),
(54, 'Outdoor Basketball Rubber', 34.99, 'basketball', 'All-weather rubber outdoor basketball size 7 with deep channels'),
(55, 'Basketball Passing Machine', 499.99, 'basketball', 'Electric ball-return machine for solo shooting and passing drills'),
(56, 'Basketball Ball Bag', 27.99, 'basketball', 'Holds up to six basketballs with shoulder strap'),
(57, 'Basketball Court Tape', 22.99, 'basketball', 'Removable adhesive court-marking tape 2 inches wide'),
(58, 'Basketball Dribble Trainer Gloves', 32.99, 'basketball', 'Perforated gloves that prevent feel, improving off-hand dribbling'),
(59, 'Basketball Vertical Jump Trainer', 79.99, 'basketball', 'Resistance band system that builds explosive jumping ability'),
(60, 'Basketball Whistle and Lanyard', 9.99, 'basketball', 'Pealess official referee whistle with braided lanyard'),

-- Hockey (20 products)
(61, 'Ice Hockey Stick', 139.99, 'hockey', 'Carbon composite one-piece stick with P28 blade pattern'),
(62, 'Hockey Helmet Combo', 89.99, 'hockey', 'ABS shell helmet with full wire cage and adjustable sizing'),
(63, 'Hockey Skates Senior', 199.99, 'hockey', 'Thermoformable boot with stainless steel blade holder'),
(64, 'Hockey Gloves', 74.99, 'hockey', '14-inch senior gloves with nylon shell and anatomic palm'),
(65, 'Hockey Shoulder Pads', 64.99, 'hockey', 'Lightweight foam shoulder and chest protector for forwards'),
(66, 'Hockey Shin Guards', 49.99, 'hockey', '16-inch shin guards with hard-shell cap and ankle wrap'),
(67, 'Hockey Elbow Pads', 39.99, 'hockey', 'Hard-cap elbow pads with stretchable sleeve integration'),
(68, 'Hockey Puck Official', 6.99, 'hockey', 'Regulation 6oz black vulcanized rubber puck for game play'),
(69, 'Goalie Stick', 159.99, 'hockey', 'Goaltender stick with wide paddle and rectangular knob'),
(70, 'Hockey Goalie Mask', 219.99, 'hockey', 'Fiberglass goalie mask with multi-directional wire cage'),
(71, 'Hockey Puck Training Pack', 19.99, 'hockey', 'Pack of six orange practice pucks for dryland training'),
(72, 'Hockey Bag with Wheels', 84.99, 'hockey', '37-inch wheeled equipment bag with ventilated skate tunnel'),
(73, 'Hockey Skate Sharpener', 49.99, 'hockey', 'Handheld sharpening tool with 1/2-inch hollow preset'),
(74, 'Hockey Jersey Authentic', 89.99, 'hockey', 'Polyester mesh practice jersey with shoulder seam lacing'),
(75, 'Hockey Stick Tape', 7.99, 'hockey', 'Cloth-backed stick tape in black 1-inch wide 25-yard roll'),
(76, 'Hockey Shooting Pad', 54.99, 'hockey', 'Synthetic ice shooting tile 4x8 feet for driveway shooting'),
(77, 'Hockey Pylon Set', 22.99, 'hockey', 'Set of 10 stickhandling pylons in bright yellow for drills'),
(78, 'Hockey Jock Shorts', 34.99, 'hockey', 'Built-in cup protective shorts with velcro sock attachment tabs'),
(79, 'Hockey Net Regulation', 179.99, 'hockey', 'Regulation 6x4 foot steel frame goal net with nylon mesh'),
(80, 'Hockey Skate Bag', 24.99, 'hockey', 'Individual ventilated skate bag with blade guards pocket'),

-- Soccer (20 products)
(81, 'Official Match Soccer Ball', 59.99, 'soccer', 'Thermally bonded panels size 5 match ball with butyl bladder'),
(82, 'Soccer Cleats Firm Ground', 69.99, 'soccer', 'Kangaroo leather upper with conical FG studs for natural grass'),
(83, 'Soccer Shin Guards', 19.99, 'soccer', 'Hard-shell polyurethane shin guards with ankle sleeves'),
(84, 'Soccer Goal Portable', 149.99, 'soccer', '8x6 foot pop-up portable goal with carry bag'),
(85, 'Soccer Goalkeeper Gloves', 44.99, 'soccer', 'Negative-cut latex palm goalkeeper gloves with wrist wrap'),
(86, 'Soccer Training Bibs Set', 24.99, 'soccer', 'Set of 12 mesh training bibs in three colors'),
(87, 'Soccer Ball Rebounder', 89.99, 'soccer', 'Adjustable bounce-back wall net for solo passing and volleys'),
(88, 'Soccer Cones Flat Disc Set', 18.99, 'soccer', 'Set of 50 flat disc cones in red yellow and blue'),
(89, 'Soccer Agility Ladder', 26.99, 'soccer', '10-meter flat ladder with 12 rungs for footwork and conditioning'),
(90, 'Soccer Ball Pump', 11.99, 'soccer', 'Dual-action ball pump with two inflation needles'),
(91, 'Soccer Jersey Short Sleeve', 29.99, 'soccer', 'Moisture-wicking polyester match jersey with side-panel vents'),
(92, 'Soccer Compression Socks', 16.99, 'soccer', 'Over-the-calf graduated compression socks in team white'),
(93, 'Soccer Speed Parachute', 22.99, 'soccer', 'Resistance training parachute for sprint speed development'),
(94, 'Soccer Tactics Board', 17.99, 'soccer', 'Magnetic pitch tactics board with player magnets and marker pen'),
(95, 'Soccer Corner Flag Set', 39.99, 'soccer', 'Set of four weighted corner flag bases with flexible poles'),
(96, 'Soccer Ball Bag Mesh', 19.99, 'soccer', 'Mesh drawstring bag with capacity for 12 size-5 soccer balls'),
(97, 'Soccer Dribble Sticks Set', 29.99, 'soccer', 'Set of 10 upright dribbling poles with flat disc bases'),
(98, 'Soccer Kick Trainer', 49.99, 'soccer', 'Adjustable solo kick trainer that returns the ball to the player'),
(99, 'Soccer Referee Kit', 34.99, 'soccer', 'Kit includes whistle, red and yellow cards, and coin'),
(100, 'Soccer Goalkeeper Jersey', 39.99, 'soccer', 'Padded elbow goalkeeper shirt in bright green with grip cuffs');